### ISSUE TITLE
somehow it doesn't compile on 2022.1

### ISSUE THREAD

**Issue by sebas77** [needle-tools/selective-profiling#21]
once installed the package, I get this error:

Library\PackageCache\com.needle.selective-profiling@1.0.1-pre.1\Editor\Chart\ChartMarkerRegistry.cs(8,19): error CS0234: The type or namespace name 'EventSystems' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
